import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Banner";
import CountOnUs from "@/components/CountOnUs";
import Loan from "@/components/LoanRequirements";
import Partners from "@/components/Partners";
import Benefits from "@/components/Benefits";
import Layout from "@/components/Layout";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Banner />
      <CountOnUs />
      <Loan />
      <Partners />
      <Benefits />
    </Layout>
    </>
  );
}
